name: Run

on:
  push:
    branches: ["main"]

jobs:
  build:
    env:
      PY_COLORS: "1"
    name: Install Dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Install
        run: |
          python -m pip install --upgrade pip wheel setuptools
          python -m pip install selenium
          python -m pip install supabase
          sudo apt install -y google-chrome-stable
          sudo apt install -y xvfb
          export DISPLAY=:0
          /usr/bin/Xvfb :0 -screen 0 1024x768x24 &
          sleep 5
          xvfb-run python run.py
      - name: done
        run: exit
